spring:
  profiles:
    include:
      - secrete


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지 1부터 시작하도록