name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]
    
env:
  APPLICATION_SECRET: ${{secrets.APPLICATION_SECRET}}
  
permissions:
  contents: read

jobs:    
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 2) JDK 11 버전 설치, 다른 JDK 버전을 사용한다면 수정 필요
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

     ## +) secrete.yml 생성 ######################
    - uses: actions/checkout@v3
    - run: touch ./src/main/resources/application-secrete.yml
    - run: echo "${{secrets.APPLICATION_SECRET}}" > ./src/main/resources/application-secrete.yml
    - run: cat ./src/main/resources/application-secrete.yml
    
    # 3) Gradle 사용. arguments 를 붙이면 뒤에 그대로 실행된다고 생각하면 됨
    # 이 워크플로우는 gradle clean build 를 수행함
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: clean build
